imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname:   "hangman"

web_profiler:
    toolbar: false
    intercept_redirects: false

