hangman_api_game_start:
    path:     /games
    defaults: { _controller: HangmanApiBundle:Hangman:gameStart }
    methods:  [POST]

hangman_api_game_guess:
    path:     /game/{id}
    defaults: { _controller: HangmanApiBundle:Hangman:gameGuess }
    methods:  [GET]
